2018-08-02 11:54:15  DEBUG    Allocating environment.
2018-08-02 11:55:32  DEBUG    Allocating environment.
2018-08-02 11:57:43  DEBUG    Allocating environment.
2018-08-02 11:58:13  DEBUG    Allocating environment.
2018-08-02 12:01:45  DEBUG    Allocating environment.
2018-08-02 12:01:45  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 12:01:45  DEBUG    Screenshot registered at post_poweron event
2018-08-02 12:01:45  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 12:01:45  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 12:01:45  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 12:01:45  DEBUG    Command execution registered at run_command event
2018-08-02 12:01:45  DEBUG    Sample execution registered at run_sample event
2018-08-02 12:01:45  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 12:01:45  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 12:01:45  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 12:01:45  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 12:01:45  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 12:01:45  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 12:01:45  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 12:01:45  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 12:01:45  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 12:01:45  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 12:01:45  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 12:01:45  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 12:01:45  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 12:01:45  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 12:01:45  DEBUG    Network tracing start registered at ip_address event
2018-08-02 12:01:45  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 12:01:45  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 12:01:45  DEBUG    Environment successfully allocated.
2018-08-02 12:01:46  INFO     Event post_poweron: starting VNC connection.
2018-08-02 12:01:46  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 12:01:46  INFO     Screenshot None captured.
2018-08-02 12:01:46  DEBUG    Waiting guest to be ready...
2018-08-02 12:01:58  DEBUG    Event ip_address: agent address <192.168.254.119>.
2018-08-02 12:01:58  DEBUG    Event ip_address: starting network tracing.
2018-08-02 12:01:58  DEBUG    Event network_tracing_started: new network trace /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/496f6289-e4d2-4a07-a224-40732bb8a49c.pcap.
2018-08-02 12:01:58  INFO     Network tracing started.
2018-08-02 12:02:58  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:02:58  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:02:58  INFO     Screenshot None captured.
2018-08-02 12:02:58  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:03:01  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_120258.bin.
2018-08-02 12:03:01  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_120258.bin taken.
2018-08-02 12:03:01  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:03:01  DEBUG    Event disk_image_start: taking disk checkpoint.
2018-08-02 12:03:04  INFO     DISK SNAPSHOT disk_image_start
2018-08-02 12:03:04  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 226, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:03:04  DEBUG    Resuming sandbox...
2018-08-02 12:03:04  DEBUG    Starting sample...
2018-08-02 12:03:04  DEBUG    Event run_sample: running command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe">.
2018-08-02 12:03:04  DEBUG    Starting new HTTP connection (1): 192.168.254.119
2018-08-02 12:03:16  DEBUG    http://192.168.254.119:8080 "POST /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 HTTP/1.1" 200 None
2018-08-02 12:03:16  INFO     Command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe"> output:
{
  "exit_code": 1,
  "command_output": "\r\n7-Zip 18.05 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30\r\n\r\nScanning the drive for archives:\r\n1 file, 8659002 bytes (8457 KiB)\r\n\r\nExtracting archive: C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmp2hh7nd6n\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\n--\r\nPath = C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmp2hh7nd6n\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\nType = zip\r\nPhysical Size = 8659002\r\n\r\nEverything is Ok\r\n\r\nFiles: 6\r\nSize:       19012048\r\nCompressed: 8659002\r\nThe system cannot find the file malware\\\"Steam Code Generator 2016.exe\\\".\r\n"
}
2018-08-02 12:04:04  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:04:04  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:04:04  INFO     Screenshot None captured.
2018-08-02 12:04:04  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:04:11  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_120404.bin.
2018-08-02 12:04:11  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_120404.bin taken.
2018-08-02 12:04:11  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:04:11  DEBUG    Event disk_image_end: taking disk checkpoint.
2018-08-02 12:04:13  INFO     DISK SNAPSHOT disk_image_end
2018-08-02 12:04:13  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 226, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/496f6289-e4d2-4a07-a224-40732bb8a49c/496f6289-e4d2-4a07-a224-40732bb8a49c': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:04:13  DEBUG    Resuming sandbox...
2018-08-02 12:04:23  DEBUG    Event post_shutdown: stopping network tracing.
2018-08-02 12:04:23  INFO     Network tracing stopped.
2018-08-02 12:04:23  ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 198, in start_processing_handler
    event, self.checkpoints[0], self.checkpoints[1])
IndexError: list index out of range
2018-08-02 12:04:23  DEBUG    Event start_analysis: starting Volatility process(es).
2018-08-02 12:04:23  DEBUG    Event start_analysis: start analysis of /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/496f6289-e4d2-4a07-a224-40732bb8a49c.pcap.
2018-08-02 12:04:23  DEBUG    Event wait_analysis: waiting for File System state comparison.
2018-08-02 12:04:32  ERROR    Unable to run carve_packets plugin.
Traceback (most recent call last):
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/memory.py", line 186, in process_snapshot
    process_memory_snapshot(snapshot, profile, plugin)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/memory.py", line 223, in process_memory_snapshot
    collect_process_output(process, file_name)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: python2 /home/nicce/Documents/Volatility/volatility/vol.py --profile=Win7SP1x86_24000 --filename=/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_120258.bin carve_packets exit code 1, output:
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : You must specify something to do (try -h)

2018-08-02 12:04:41  ERROR    Unable to run carve_packets plugin.
Traceback (most recent call last):
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/memory.py", line 186, in process_snapshot
    process_memory_snapshot(snapshot, profile, plugin)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/memory.py", line 223, in process_memory_snapshot
    collect_process_output(process, file_name)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: python2 /home/nicce/Documents/Volatility/volatility/vol.py --profile=Win7SP1x86_24000 --filename=/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_120404.bin carve_packets exit code 1, output:
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : You must specify something to do (try -h)

2018-08-02 12:06:15  DEBUG    Deallocating environment.
2018-08-02 12:06:16  DEBUG    Environment successfully deallocated.
2018-08-02 12:09:54  DEBUG    Allocating environment.
2018-08-02 12:09:54  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 12:09:54  DEBUG    Screenshot registered at post_poweron event
2018-08-02 12:09:54  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 12:09:54  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 12:09:54  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 12:09:54  DEBUG    Command execution registered at run_command event
2018-08-02 12:09:54  DEBUG    Sample execution registered at run_sample event
2018-08-02 12:09:54  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 12:09:54  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 12:09:54  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 12:09:54  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 12:09:54  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 12:09:54  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 12:09:54  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 12:09:54  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 12:09:54  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 12:09:54  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 12:09:54  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 12:09:54  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 12:09:54  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 12:09:54  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 12:09:54  DEBUG    Network tracing start registered at ip_address event
2018-08-02 12:09:54  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 12:09:54  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 12:09:54  DEBUG    Environment successfully allocated.
2018-08-02 12:09:55  INFO     Event post_poweron: starting VNC connection.
2018-08-02 12:09:55  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 12:09:55  INFO     Screenshot None captured.
2018-08-02 12:09:55  DEBUG    Waiting guest to be ready...
2018-08-02 12:10:07  DEBUG    Event ip_address: agent address <192.168.254.155>.
2018-08-02 12:10:07  DEBUG    Event ip_address: starting network tracing.
2018-08-02 12:10:07  DEBUG    Event network_tracing_started: new network trace /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/1b3f5cb7-d19e-4508-b930-e4d3123a101b.pcap.
2018-08-02 12:10:07  INFO     Network tracing started.
2018-08-02 12:11:07  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:11:07  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:11:07  INFO     Screenshot None captured.
2018-08-02 12:11:07  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:11:10  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_121107.bin.
2018-08-02 12:11:10  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_121107.bin taken.
2018-08-02 12:11:10  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:11:10  DEBUG    Event disk_image_start: taking disk checkpoint.
2018-08-02 12:11:12  INFO     DISK SNAPSHOT disk_image_start
2018-08-02 12:11:12  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 226, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:11:12  DEBUG    Resuming sandbox...
2018-08-02 12:11:12  DEBUG    Starting sample...
2018-08-02 12:11:12  DEBUG    Event run_sample: running command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe">.
2018-08-02 12:11:12  DEBUG    Starting new HTTP connection (1): 192.168.254.155
2018-08-02 12:12:12  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:12:12  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:12:13  INFO     Screenshot None captured.
2018-08-02 12:12:13  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:12:20  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_121213.bin.
2018-08-02 12:12:20  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_121213.bin taken.
2018-08-02 12:12:20  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:12:20  DEBUG    Event disk_image_end: taking disk checkpoint.
2018-08-02 12:12:22  INFO     DISK SNAPSHOT disk_image_end
2018-08-02 12:12:22  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 226, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/1b3f5cb7-d19e-4508-b930-e4d3123a101b/1b3f5cb7-d19e-4508-b930-e4d3123a101b': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:12:22  DEBUG    Resuming sandbox...
2018-08-02 12:12:22  DEBUG    http://192.168.254.155:8080 "POST /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 HTTP/1.1" 200 None
2018-08-02 12:12:22  INFO     Command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe"> output:
{
  "exit_code": 1073807364,
  "command_output": "\r\n7-Zip 18.05 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30\r\n\r\nScanning the drive for archives:\r\n1 file, 8659002 bytes (8457 KiB)\r\n\r\nExtracting archive: C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpjj24ften\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\n--\r\nPath = C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpjj24ften\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\nType = zip\r\nPhysical Size = 8659002\r\n\r\nEverything is Ok\r\n\r\nFiles: 6\r\nSize:       19012048\r\nCompressed: 8659002\r\n"
}
2018-08-02 12:12:35  DEBUG    Event post_shutdown: stopping network tracing.
2018-08-02 12:12:35  INFO     Network tracing stopped.
2018-08-02 12:12:35  ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 198, in start_processing_handler
    event, self.checkpoints[0], self.checkpoints[1])
IndexError: list index out of range
2018-08-02 12:12:35  DEBUG    Event start_analysis: starting Volatility process(es).
2018-08-02 12:12:35  DEBUG    Event start_analysis: start analysis of /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/1b3f5cb7-d19e-4508-b930-e4d3123a101b.pcap.
2018-08-02 12:12:35  DEBUG    Event wait_analysis: waiting for File System state comparison.
2018-08-02 12:18:29  DEBUG    Deallocating environment.
2018-08-02 12:18:29  DEBUG    Environment successfully deallocated.
2018-08-02 12:18:36  DEBUG    Allocating environment.
2018-08-02 12:18:36  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 12:18:36  DEBUG    Screenshot registered at post_poweron event
2018-08-02 12:18:36  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 12:18:36  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 12:18:36  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 12:18:36  DEBUG    Command execution registered at run_command event
2018-08-02 12:18:36  DEBUG    Sample execution registered at run_sample event
2018-08-02 12:18:36  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 12:18:36  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 12:18:36  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 12:18:36  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 12:18:36  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 12:18:36  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 12:18:36  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 12:18:36  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 12:18:36  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 12:18:36  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 12:18:36  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 12:18:36  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 12:18:36  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 12:18:36  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 12:18:36  DEBUG    Network tracing start registered at ip_address event
2018-08-02 12:18:36  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 12:18:36  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 12:18:36  DEBUG    Environment successfully allocated.
2018-08-02 12:18:38  INFO     Event post_poweron: starting VNC connection.
2018-08-02 12:18:38  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 12:18:38  INFO     Screenshot None captured.
2018-08-02 12:18:38  DEBUG    Waiting guest to be ready...
2018-08-02 12:18:53  DEBUG    Event ip_address: agent address <192.168.254.94>.
2018-08-02 12:18:53  DEBUG    Event ip_address: starting network tracing.
2018-08-02 12:18:53  DEBUG    Event network_tracing_started: new network trace /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/ed93e205-4e6f-4daf-ac69-7c41a89a7016.pcap.
2018-08-02 12:18:53  INFO     Network tracing started.
2018-08-02 12:19:53  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:19:53  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:19:53  INFO     Screenshot None captured.
2018-08-02 12:19:53  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:19:57  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_121953.bin.
2018-08-02 12:19:57  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_121953.bin taken.
2018-08-02 12:19:57  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:20:57  DEBUG    Event disk_image_start: taking disk checkpoint.
2018-08-02 12:21:01  INFO     DISK SNAPSHOT disk_image_start
2018-08-02 12:21:01  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 227, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:21:01  DEBUG    Resuming sandbox...
2018-08-02 12:21:01  DEBUG    Starting sample...
2018-08-02 12:21:01  DEBUG    Event run_sample: running command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe">.
2018-08-02 12:21:01  DEBUG    Starting new HTTP connection (1): 192.168.254.94
2018-08-02 12:21:24  DEBUG    http://192.168.254.94:8080 "POST /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 HTTP/1.1" 200 None
2018-08-02 12:21:24  INFO     Command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe"> output:
{
  "exit_code": 1,
  "command_output": "\r\n7-Zip 18.05 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30\r\n\r\nScanning the drive for archives:\r\n1 file, 8659002 bytes (8457 KiB)\r\n\r\nExtracting archive: C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpz4wcjb88\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\n--\r\nPath = C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpz4wcjb88\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\nType = zip\r\nPhysical Size = 8659002\r\n\r\nEverything is Ok\r\n\r\nFiles: 6\r\nSize:       19012048\r\nCompressed: 8659002\r\nThe system cannot find the file malware\\\"Steam Code Generator 2016.exe\\\".\r\n"
}
2018-08-02 12:22:01  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:22:01  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:22:01  INFO     Screenshot None captured.
2018-08-02 12:22:01  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:22:04  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_122201.bin.
2018-08-02 12:22:04  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_122201.bin taken.
2018-08-02 12:22:04  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:23:04  DEBUG    Event disk_image_end: taking disk checkpoint.
2018-08-02 12:23:07  INFO     DISK SNAPSHOT disk_image_end
2018-08-02 12:23:07  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 227, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/ed93e205-4e6f-4daf-ac69-7c41a89a7016/ed93e205-4e6f-4daf-ac69-7c41a89a7016': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:23:07  DEBUG    Resuming sandbox...
2018-08-02 12:23:23  DEBUG    Event post_shutdown: stopping network tracing.
2018-08-02 12:23:23  INFO     Network tracing stopped.
2018-08-02 12:23:23  ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 199, in start_processing_handler
    event, self.checkpoints[0], self.checkpoints[1])
IndexError: list index out of range
2018-08-02 12:23:23  DEBUG    Event start_analysis: starting Volatility process(es).
2018-08-02 12:23:23  DEBUG    Event start_analysis: start analysis of /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/ed93e205-4e6f-4daf-ac69-7c41a89a7016.pcap.
2018-08-02 12:23:23  DEBUG    Event wait_analysis: waiting for File System state comparison.
2018-08-02 12:28:55  DEBUG    Deallocating environment.
2018-08-02 12:28:56  DEBUG    Environment successfully deallocated.
2018-08-02 12:28:58  DEBUG    Allocating environment.
2018-08-02 12:28:58  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 12:28:58  DEBUG    Screenshot registered at post_poweron event
2018-08-02 12:28:58  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 12:28:58  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 12:28:58  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 12:28:58  DEBUG    Command execution registered at run_command event
2018-08-02 12:28:58  DEBUG    Sample execution registered at run_sample event
2018-08-02 12:28:58  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 12:28:58  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 12:28:58  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 12:28:58  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 12:28:58  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 12:28:58  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 12:28:58  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 12:28:58  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 12:28:58  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 12:28:58  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 12:28:58  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 12:28:58  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 12:28:58  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 12:28:58  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 12:28:58  DEBUG    Network tracing start registered at ip_address event
2018-08-02 12:28:58  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 12:28:58  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 12:28:58  DEBUG    Environment successfully allocated.
2018-08-02 12:28:59  INFO     Event post_poweron: starting VNC connection.
2018-08-02 12:28:59  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 12:28:59  INFO     Screenshot None captured.
2018-08-02 12:28:59  DEBUG    Waiting guest to be ready...
2018-08-02 12:29:13  DEBUG    Event ip_address: agent address <192.168.254.28>.
2018-08-02 12:29:13  DEBUG    Event ip_address: starting network tracing.
2018-08-02 12:29:13  DEBUG    Event network_tracing_started: new network trace /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/77c2480d-bd2a-4c22-b647-abe2148fb093.pcap.
2018-08-02 12:29:13  INFO     Network tracing started.
2018-08-02 12:30:13  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:30:13  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:30:13  INFO     Screenshot None captured.
2018-08-02 12:30:13  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:30:16  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_123013.bin.
2018-08-02 12:30:16  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_123013.bin taken.
2018-08-02 12:30:16  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:31:16  DEBUG    Event disk_image_start: taking disk checkpoint.
2018-08-02 12:31:18  INFO     DISK SNAPSHOT disk_image_start
2018-08-02 12:31:18  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 226, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_start /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:31:18  DEBUG    Resuming sandbox...
2018-08-02 12:31:18  DEBUG    Starting sample...
2018-08-02 12:31:18  DEBUG    Event run_sample: running command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe">.
2018-08-02 12:31:19  DEBUG    Starting new HTTP connection (1): 192.168.254.28
2018-08-02 12:32:19  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:32:19  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:32:19  INFO     Screenshot None captured.
2018-08-02 12:32:19  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:32:25  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_123219.bin.
2018-08-02 12:32:25  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_123219.bin taken.
2018-08-02 12:32:25  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:33:25  DEBUG    Event disk_image_end: taking disk checkpoint.
2018-08-02 12:33:28  INFO     DISK SNAPSHOT disk_image_end
2018-08-02 12:33:28  ERROR    qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093': Failed to get shared "write" lock
Is another process using the image?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 89, in disk_checkpoint_handler
    checkpoint_path = self.disk_checkpoint(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 101, in disk_checkpoint
    self.configuration['results_folder'])
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 226, in snapshot_to_checkpoint
    collect_process_output(process)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/utils.py", line 39, in collect_process_output
    % (' '.join(process.args), process.returncode, output))
RuntimeError: qemu-img convert -f qcow2 -o backing_file=/home/nicce/Documents/libvirt_images/win7image.qcow2 -O qcow2 -s disk_image_end /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093 /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 exit code 1, output:
qemu-img: Could not open '/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/instances/77c2480d-bd2a-4c22-b647-abe2148fb093/77c2480d-bd2a-4c22-b647-abe2148fb093': Failed to get shared "write" lock
Is another process using the image?

2018-08-02 12:33:28  DEBUG    Resuming sandbox...
2018-08-02 12:33:28  ERROR    ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/commands.py", line 95, in run_sample_handler
    response = self.sample_request(event.command, event.sample, async)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/commands.py", line 116, in sample_request
    'async': int(async)})
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2018-08-02 12:33:43  DEBUG    Event post_shutdown: stopping network tracing.
2018-08-02 12:33:43  INFO     Network tracing stopped.
2018-08-02 12:33:43  ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 198, in start_processing_handler
    event, self.checkpoints[0], self.checkpoints[1])
IndexError: list index out of range
2018-08-02 12:33:43  DEBUG    Event start_analysis: start analysis of /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/77c2480d-bd2a-4c22-b647-abe2148fb093.pcap.
2018-08-02 12:33:43  DEBUG    Event start_analysis: starting Volatility process(es).
2018-08-02 12:33:43  DEBUG    Event wait_analysis: waiting for File System state comparison.
2018-08-02 12:33:53  DEBUG    Deallocating environment.
2018-08-02 12:33:53  ERROR    Unable to delete storage pool folder.
Traceback (most recent call last):
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/sandbox.py", line 33, in main
    protocol(environment.context, arguments.sample, arguments.command)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/sandbox.py", line 47, in protocol
    context.trigger('wait_analysis')
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 108, in trigger
    synchronous(handler, event)
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 211, in stop_processing_handler
    self.processing_done.wait()
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/context/resources/qemu.py", line 270, in pool_delete
    shutil.rmtree(path)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '77c2480d-bd2a-4c22-b647-abe2148fb093_start'
2018-08-02 12:33:53  DEBUG    Environment successfully deallocated.
2018-08-02 12:43:57  DEBUG    Allocating environment.
2018-08-02 12:43:57  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 12:43:57  DEBUG    Screenshot registered at post_poweron event
2018-08-02 12:43:57  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 12:43:57  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 12:43:57  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 12:43:57  DEBUG    Command execution registered at run_command event
2018-08-02 12:43:57  DEBUG    Sample execution registered at run_sample event
2018-08-02 12:43:57  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 12:43:57  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 12:43:57  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 12:43:57  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 12:43:57  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 12:43:57  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 12:43:57  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 12:43:57  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 12:43:57  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 12:43:57  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 12:43:57  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 12:43:57  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 12:43:57  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 12:43:57  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 12:43:57  DEBUG    Network tracing start registered at ip_address event
2018-08-02 12:43:57  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 12:43:57  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 12:43:57  DEBUG    Environment successfully allocated.
2018-08-02 12:43:58  INFO     Event post_poweron: starting VNC connection.
2018-08-02 12:43:58  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 12:43:59  INFO     Screenshot None captured.
2018-08-02 12:43:59  DEBUG    Waiting guest to be ready...
2018-08-02 12:44:13  DEBUG    Event ip_address: agent address <192.168.254.224>.
2018-08-02 12:44:13  DEBUG    Event ip_address: starting network tracing.
2018-08-02 12:44:13  DEBUG    Event network_tracing_started: new network trace /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/4c4c2472-4d33-4dff-99a6-21de0d81245a.pcap.
2018-08-02 12:44:13  INFO     Network tracing started.
2018-08-02 12:45:13  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:45:13  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:45:13  INFO     Screenshot None captured.
2018-08-02 12:45:13  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:45:21  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_124513.bin.
2018-08-02 12:45:21  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_124513.bin taken.
2018-08-02 12:45:21  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:46:21  DEBUG    Event disk_image_start: taking disk checkpoint.
2018-08-02 12:46:23  INFO     DISK SNAPSHOT disk_image_start
2018-08-02 12:46:23  INFO     DISK PATH /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2
2018-08-02 12:46:23  DEBUG    Event disk_checkpoint_taken: new disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2.
2018-08-02 12:46:23  INFO     Disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 taken.
2018-08-02 12:46:23  DEBUG    Resuming sandbox...
2018-08-02 12:46:23  DEBUG    Starting sample...
2018-08-02 12:46:23  DEBUG    Event run_sample: running command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe">.
2018-08-02 12:46:23  DEBUG    Starting new HTTP connection (1): 192.168.254.224
2018-08-02 12:47:23  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 12:47:23  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 12:47:23  INFO     Screenshot None captured.
2018-08-02 12:47:23  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 12:47:30  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_124723.bin.
2018-08-02 12:47:30  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_124723.bin taken.
2018-08-02 12:47:30  DEBUG    Finished. Taking disk snapshot...
2018-08-02 12:48:30  DEBUG    Event disk_image_end: taking disk checkpoint.
2018-08-02 12:48:33  ERROR    HTTPConnectionPool(host='192.168.254.224', port=8080): Max retries exceeded with url: /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3fb57db38>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa3fb57db38>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nicce/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.254.224', port=8080): Max retries exceeded with url: /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3fb57db38>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/commands.py", line 95, in run_sample_handler
    response = self.sample_request(event.command, event.sample, async)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/commands.py", line 116, in sample_request
    'async': int(async)})
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/nicce/.local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.254.224', port=8080): Max retries exceeded with url: /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3fb57db38>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2018-08-02 12:48:36  INFO     DISK SNAPSHOT disk_image_end
2018-08-02 12:48:36  INFO     DISK PATH /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2
2018-08-02 12:48:36  DEBUG    Event disk_checkpoint_taken: new disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2.
2018-08-02 12:48:36  INFO     Disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 taken.
2018-08-02 12:48:36  DEBUG    Resuming sandbox...
2018-08-02 12:48:51  DEBUG    Event post_shutdown: stopping network tracing.
2018-08-02 12:48:52  INFO     Network tracing stopped.
2018-08-02 12:48:52  DEBUG    Event start_analysis: start comparing /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 with /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2.
2018-08-02 12:48:52  DEBUG    Event start_analysis: starting Volatility process(es).
2018-08-02 12:48:52  DEBUG    Event start_analysis: start analysis of /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/4c4c2472-4d33-4dff-99a6-21de0d81245a.pcap.
2018-08-02 12:48:52  DEBUG    Event wait_analysis: waiting for File System state comparison.
2018-08-02 12:48:59  DEBUG    Comparing FS contents.
2018-08-02 12:48:59  WARNING  Error hashing disk /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 contents, iterating over files.
2018-08-02 12:48:59  WARNING  Error hashing disk /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 contents, iterating over files.
2018-08-02 12:48:59  ERROR    file receive cancelled by daemon
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 204, in hash_filesystem
    return dict(filesystem.checksums('/'))
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 160, in checksums
    tempfile.name)
  File "/usr/local/lib/python3.6/dist-packages/guestfs.py", line 1919, in checksums_out
    r = libguestfsmod.checksums_out(self._o, csumtype, directory, sumsfile)
RuntimeError: file receive cancelled by daemon

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 201, in start_processing_handler
    self.configuration)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 238, in compare_disks
    concurrent=configuration.get('use_concurrency', False))
  File "/usr/local/lib/python3.6/dist-packages/vminspect/comparator.py", line 91, in compare
    concurrent=concurrent)
  File "/usr/local/lib/python3.6/dist-packages/vminspect/comparator.py", line 195, in compare_filesystems
    files0 = future0.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/pebble/concurrent/thread.py", line 47, in _function_handler
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/vminspect/comparator.py", line 389, in concurrent_hash_filesystem
    return hash_filesystem(filesystem)
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 211, in hash_filesystem
    for path in filesystem.nodes('/'):
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 140, in nodes
    yield from (self.path(path, e) for e in self._handler.find(path))
  File "/usr/local/lib/python3.6/dist-packages/guestfs.py", line 3125, in find
    r = libguestfsmod.find(self._o, directory)
RuntimeError: file receive cancelled by daemon
2018-08-02 13:00:55  DEBUG    Deallocating environment.
2018-08-02 13:00:56  DEBUG    Environment successfully deallocated.
2018-08-02 13:00:58  DEBUG    Allocating environment.
2018-08-02 13:02:02  DEBUG    Allocating environment.
2018-08-02 13:02:03  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 13:02:03  DEBUG    Screenshot registered at post_poweron event
2018-08-02 13:02:03  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 13:02:03  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 13:02:03  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 13:02:03  DEBUG    Command execution registered at run_command event
2018-08-02 13:02:03  DEBUG    Sample execution registered at run_sample event
2018-08-02 13:02:03  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 13:02:03  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 13:02:03  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 13:02:03  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 13:02:03  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 13:02:03  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 13:02:03  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 13:02:03  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 13:02:03  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 13:02:03  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 13:02:03  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 13:02:03  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 13:02:03  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 13:02:03  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 13:02:03  DEBUG    Network tracing start registered at ip_address event
2018-08-02 13:02:03  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 13:02:03  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 13:02:03  DEBUG    Environment successfully allocated.
2018-08-02 13:02:04  INFO     Event post_poweron: starting VNC connection.
2018-08-02 13:02:04  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 13:02:04  INFO     Screenshot None captured.
2018-08-02 13:02:04  DEBUG    Waiting guest to be ready...
2018-08-02 13:02:09  DEBUG    Deallocating environment.
2018-08-02 13:02:10  DEBUG    Environment successfully deallocated.
2018-08-02 13:09:40  DEBUG    Allocating environment.
2018-08-02 13:09:40  DEBUG    Loading hooks.screenhook.ScreenHook hook.
2018-08-02 13:09:40  DEBUG    Screenshot registered at post_poweron event
2018-08-02 13:09:40  DEBUG    Screenshot registered at snapshots_capture event
2018-08-02 13:09:40  DEBUG    Loading hooks.vnchook.VNCHook hook.
2018-08-02 13:09:40  DEBUG    Loading hooks.commands.CommandsHook hook.
2018-08-02 13:09:40  DEBUG    Command execution registered at run_command event
2018-08-02 13:09:40  DEBUG    Sample execution registered at run_sample event
2018-08-02 13:09:40  DEBUG    Loading hooks.disk.DiskCheckPointHook hook.
2018-08-02 13:09:40  DEBUG    Disk checkpoint registered at iip_address event
2018-08-02 13:09:40  DEBUG    Disk checkpoint registered at ppost_shutdown event
2018-08-02 13:09:40  DEBUG    Disk checkpoint registered at disk_image_start event
2018-08-02 13:09:40  DEBUG    Disk checkpoint registered at disk_image_end event
2018-08-02 13:09:40  DEBUG    Loading hooks.disk.DiskStateAnalyser hook.
2018-08-02 13:09:40  DEBUG    FileSystem analysis scheduled at start_analysis event
2018-08-02 13:09:40  DEBUG    FileSystem analysis wait at wait_analysis event
2018-08-02 13:09:40  DEBUG    Loading hooks.memory.MemoryHook hook.
2018-08-02 13:09:40  DEBUG    Memory snapshot registered at snapshots_capture event
2018-08-02 13:09:40  DEBUG    Loading hooks.memory.VolatilityHook hook.
2018-08-02 13:09:40  DEBUG    Volatility scheduled at start_analysis event
2018-08-02 13:09:40  DEBUG    Volatility processing wait at wait_analysis event
2018-08-02 13:09:40  DEBUG    Loading hooks.network.NetworkTracerHook hook.
2018-08-02 13:09:40  DEBUG    Network tracing start registered at ip_address event
2018-08-02 13:09:40  DEBUG    Network tracing stop registered at post_shutdown event
2018-08-02 13:09:40  DEBUG    Loading hooks.network.NetworkAnalysisHook hook.
2018-08-02 13:09:40  DEBUG    Environment successfully allocated.
2018-08-02 13:09:41  INFO     Event post_poweron: starting VNC connection.
2018-08-02 13:09:41  DEBUG    Event post_poweron: capturing screenshot.
2018-08-02 13:09:42  INFO     Screenshot None captured.
2018-08-02 13:09:42  DEBUG    Waiting guest to be ready...
2018-08-02 13:09:56  DEBUG    Event ip_address: agent address <192.168.254.179>.
2018-08-02 13:09:56  DEBUG    Event ip_address: starting network tracing.
2018-08-02 13:09:56  DEBUG    Event network_tracing_started: new network trace /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/8ce253de-69ac-4903-b03a-28c5c8f3ce85.pcap.
2018-08-02 13:09:56  INFO     Network tracing started.
2018-08-02 13:10:56  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 13:10:56  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 13:10:56  INFO     Screenshot None captured.
2018-08-02 13:10:56  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 13:11:02  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_131056.bin.
2018-08-02 13:11:02  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_131056.bin taken.
2018-08-02 13:11:02  DEBUG    Finished. Taking disk snapshot...
2018-08-02 13:12:02  DEBUG    Event disk_image_start: taking disk checkpoint.
2018-08-02 13:12:04  INFO     DISK SNAPSHOT disk_image_start
2018-08-02 13:12:04  INFO     DISK PATH /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2
2018-08-02 13:12:04  DEBUG    Event disk_checkpoint_taken: new disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2.
2018-08-02 13:12:04  INFO     Disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 taken.
2018-08-02 13:12:04  DEBUG    Resuming sandbox...
2018-08-02 13:12:04  DEBUG    Starting sample...
2018-08-02 13:12:04  DEBUG    Event run_sample: running command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe">.
2018-08-02 13:12:04  DEBUG    Starting new HTTP connection (1): 192.168.254.179
2018-08-02 13:12:22  DEBUG    http://192.168.254.179:8080 "POST /?command=7z+x+%7Bsample%7D+-omalware%2F+%26%26+start+malware%22Steam+Code+Generator+2016.exe%22&sample=56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip&async=0 HTTP/1.1" 200 None
2018-08-02 13:12:22  INFO     Command <7z x {sample} -omalware/ && start malware"Steam Code Generator 2016.exe"> output:
{
  "exit_code": 1,
  "command_output": "\r\n7-Zip 18.05 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30\r\n\r\nScanning the drive for archives:\r\n1 file, 8659002 bytes (8457 KiB)\r\n\r\nExtracting archive: C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpn3kgnxl0\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\n--\r\nPath = C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpn3kgnxl0\\56ac0dc0df10ea41ec4ead6d6f538816e5a4a61bfb7a65dfb5a265158be7f4fe.zip\r\nType = zip\r\nPhysical Size = 8659002\r\n\r\nEverything is Ok\r\n\r\nFiles: 6\r\nSize:       19012048\r\nCompressed: 8659002\r\nThe system cannot find the file malware\\\"Steam Code Generator 2016.exe\\\".\r\n"
}
2018-08-02 13:13:04  DEBUG    Pausing sandbox. Taking memory snapshot...
2018-08-02 13:13:04  DEBUG    Event snapshots_capture: capturing screenshot.
2018-08-02 13:13:04  INFO     Screenshot None captured.
2018-08-02 13:13:04  DEBUG    Event snapshots_capture: taking memory snapshot.
2018-08-02 13:13:07  DEBUG    Event memory_snapshot_taken: new memory dump /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_131304.bin.
2018-08-02 13:13:07  INFO     Memory snapshot /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/memlogs/snapshots_capture_131304.bin taken.
2018-08-02 13:13:07  DEBUG    Finished. Taking disk snapshot...
2018-08-02 13:14:08  DEBUG    Event disk_image_end: taking disk checkpoint.
2018-08-02 13:14:12  INFO     DISK SNAPSHOT disk_image_end
2018-08-02 13:14:12  INFO     DISK PATH /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2
2018-08-02 13:14:12  DEBUG    Event disk_checkpoint_taken: new disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2.
2018-08-02 13:14:12  INFO     Disk checkpoint /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2 taken.
2018-08-02 13:14:12  DEBUG    Resuming sandbox...
2018-08-02 13:14:25  DEBUG    Event post_shutdown: stopping network tracing.
2018-08-02 13:14:25  INFO     Network tracing stopped.
2018-08-02 13:14:25  DEBUG    Event start_analysis: start comparing /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 with /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_end.qcow2.
2018-08-02 13:14:25  DEBUG    Event start_analysis: starting Volatility process(es).
2018-08-02 13:14:25  DEBUG    Event start_analysis: start analysis of /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/network/8ce253de-69ac-4903-b03a-28c5c8f3ce85.pcap.
2018-08-02 13:14:25  DEBUG    Event wait_analysis: waiting for File System state comparison.
2018-08-02 13:14:30  DEBUG    Comparing FS contents.
2018-08-02 13:14:30  WARNING  Error hashing disk /home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/disklogs/disk_image_start.qcow2 contents, iterating over files.
2018-08-02 13:14:30  ERROR    file receive cancelled by daemon
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 204, in hash_filesystem
    return dict(filesystem.checksums('/'))
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 160, in checksums
    tempfile.name)
  File "/usr/local/lib/python3.6/dist-packages/guestfs.py", line 1919, in checksums_out
    r = libguestfsmod.checksums_out(self._o, csumtype, directory, sumsfile)
RuntimeError: file receive cancelled by daemon

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/see/observer.py", line 142, in synchronous
    function(event)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 201, in start_processing_handler
    self.configuration)
  File "/home/nicce/Desktop/CompSec/Lab4.Botnets_and_malwares/see/hooks/disk.py", line 238, in compare_disks
    concurrent=configuration.get('use_concurrency', False))
  File "/usr/local/lib/python3.6/dist-packages/vminspect/comparator.py", line 91, in compare
    concurrent=concurrent)
  File "/usr/local/lib/python3.6/dist-packages/vminspect/comparator.py", line 198, in compare_filesystems
    files0 = hash_filesystem(fs0)
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 211, in hash_filesystem
    for path in filesystem.nodes('/'):
  File "/usr/local/lib/python3.6/dist-packages/vminspect/filesystem.py", line 140, in nodes
    yield from (self.path(path, e) for e in self._handler.find(path))
  File "/usr/local/lib/python3.6/dist-packages/guestfs.py", line 3125, in find
    r = libguestfsmod.find(self._o, directory)
RuntimeError: file receive cancelled by daemon
2018-08-02 14:05:31  DEBUG    Deallocating environment.
2018-08-02 14:05:31  DEBUG    Environment successfully deallocated.
